export const INIT_APPOINTMENT = 'INIT_APPOINTMENT';

  export const SCHEDULE_APPOINTMENT = {
    START: 'SCHEDULE_APPOINTMENT_START',
    SUCCESS: 'SCHEDULE_APPOINTMENT_SUCCESS',
    ERROR: 'SCHEDULE_APPOINTMENT_ERROR',
  };
  
  export const CANCEL_APPOINTMENT = {
    START: 'CANCEL_APPOINTMENT_START',
    SUCCESS: 'CANCEL_APPOINTMENT_SUCCESS',
    ERROR: 'CANCEL_APPOINTMENT_ERROR',
  };
  