export const FETCH_DOCTORS = {
    START: 'FETCH_DOCTORS_START',
    SUCCESS: 'FETCH_DOCTORS_SUCCESS',
    ERROR: 'FETCH_DOCTORS_ERROR',
  }
  
  export const INIT_DOCTORS = 'INIT_DOCTORS'
  
  export const ADD_DOCTOR_DETAILS = {
    START: 'ADD_DOCTOR_DETAILS_START',
    SUCCESS: 'ADD_DOCTOR_DETAILS_SUCCESS',
    ERROR: 'ADD_DOCTOR_DETAILS_ERROR',
  };
  